# Generated by Django 5.2.9 on 2025-12-03 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_redirect_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BandDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='CoverAlbum',
        ),
        migrations.AddField(
            model_name='band',
            name='finalizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='fundacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='genero',
            field=models.ManyToManyField(to='lyrics_redirect_django.musicalgenre'),
        ),
        migrations.AddField(
            model_name='band',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicalgenre',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(to='lyrics_redirect_django.musicalgenre'),
        ),
        migrations.AddField(
            model_name='song',
            name='lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='tempo_musica',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='url_musica',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='album',
            name='genero',
            field=models.ManyToManyField(to='lyrics_redirect_django.musicalgenre'),
        ),
        migrations.AddField(
            model_name='album',
            name='musica',
            field=models.ManyToManyField(to='lyrics_redirect_django.song'),
        ),
        migrations.AddField(
            model_name='band',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyrics_redirect_django.album'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lyrics_redirect_django.albumdescription'),
        ),
        migrations.AddField(
            model_name='band',
            name='band_description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lyrics_redirect_django.banddescription'),
        ),
    ]
