# Generated by Django 5.2.9 on 2025-12-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_redirect_django', '0002_album_albumdescription_banddescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tempo_musica',
            field=models.IntegerField(),
        ),
    ]
