# Generated by Django 5.2.9 on 2025-12-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_redirect_django', '0003_alter_song_tempo_musica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='lyrics_redirect_django.band'),
        ),
    ]
